apiVersion: v1
kind: Service
metadata:
  name: kubia
  labels:
    app: kubia
    rel: beta
spec:
  sessionAffinity: ClientIP
  selector:
    app: kubia
  ports:
    - port: 80
      name: http
      targetPort: http
    - port: 443
      name: https
      targetPort: https
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
  labels:
    app: kubia
    rel: beta
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["kubia"]
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
        rel: beta
    spec:
      containers:
        - name: main
          image: sm123tt/kubia:v2
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 8080
              path: /
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: extweb
  labels:
    app: extweb
    rel: beta
spec:
  type: NodePort
  selector:
    app: extweb
  ports:
    - port: 80
      nodePort: 30123
      name: http
      targetPort: http
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: extweb
  labels:
    app: extweb
    rel: beta
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["extweb"]
  template:
    metadata:
      name: extweb
      labels:
        app: extweb
        rel: beta
    spec:
      containers:
        - name: main
          image: sm123tt/extweb:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 10
            httpGet:
              port: http
              path: /users