apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
  labels:
    app: kubia
    chapter: "5"
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["kubia"]
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
        chapter: "5"
    spec:
      containers:
        - name: main
          image: sm123tt/kubia:v2
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: http
              path: /
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: http
              path: /
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kubia
  labels:
    app: kubia
    chapter: "5"
spec:
  selector:
    app: kubia
  ports:
    - port: 80
      targetPort: http
      name: http
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-api
  labels:
    app: user-api
    chapter: "5"
spec:
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["user-api"]
  template:
    metadata:
      name: user-api
      labels:
        app: user-api
        chapter: "5"
    spec:
      containers:
        - name: main
          image: sm123tt/user-api:v1
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 8080
              path: /users
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 8080
              path: /users
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    app: user-api
    chapter: "5"
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
    - port: 80
      targetPort: http
      name: http
      nodePort: 30125
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  labels:
    app: my-ingress
    chapter: "5"
spec:
  tls:
    - hosts: ["kubia.example.com"]
      secretName: tls-cert
  rules:
    - host: "kubia.example.com"
      http:
        paths:
          - backend:
              serviceName: user-api
              servicePort: 80
            path: /user-api
          - backend:
              serviceName: kubia
              servicePort: 80
            path: /kubia
      