---
apiVersion: v1
kind: Service
metadata:
  name: fortune
  labels:
    app: fortune
    chapter: "6"
spec:
  selector:
    app: fortune
  ports:
    - port: 80
      name: http
      targetPort: http
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: fortune
  labels:
    app: fortune
    chapter: "6"
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["fortune"]
  template:
    metadata:
      name: fortune
      labels:
        app: fortune
        chapter: "6"
    spec:
      containers:
        - name: html-generator
          image: sm123tt/fortune:v1
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/htdocs
              name: html
          readinessProbe:
            initialDelaySeconds: 10
            exec:
              command:
                - "ls"
        - name: web-server
          image: nginx:alpine 
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html
              readOnly: true
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: http
              path: /
      volumes:
        - name: html
          emptyDir: {}
              
          