apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  labels:
    app: mongodb
    chapter: "6"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: mongodb
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb
  labels:
    app: mongodb
    chapter: "6"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodb
  labels:
    app: mongodb
    chapter: "6"
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["mongodb"]
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
        chapter: "6"
    spec:
      containers:
        - name: mongo
          image: mongo
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
    