apiVersion: apps/v1
kind: ReplicaSet
metadata:
  namespace: prac
  name: kubia
  labels:
    app: kubia
    chapter: prac
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["kubia"]
  template:
    metadata:
      namespace: prac
      name: kubia
      labels:
        app: kubia
        chapter: prac
    spec:
      containers:
        - name: main
          image: sm123tt/kubia-node:v1
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: http
              path: /
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP