apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: ["kubia"]
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: sm123tt/kubia:v1
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              port: http
              path: /